const products = [

    {name : "Face Wash", companyName : "ORGATRE", category : "beauty",src : "assets/IMAGES/Beauty/antiaging Face wash.png",off: 10, trending: false,price : 1299, des : "lorem1234"},
    {name : "Body Lotion", companyName : "eos", category : "beauty",src : "assets/IMAGES/Beauty/Body lotion.png",off: 0, trending: false,price : 449, des : "lorem1234"},
    {name : "Body Scrub", companyName : "Dove", category : "beauty",src : "assets/IMAGES/Beauty/Body Scrub.png",off: 10, trending: false, price : 599, des : "lorem1234"},
    {name : "Eyeshadow", companyName : "Huda Beauty", category : "beauty",src : "assets/IMAGES/Beauty/Eyeshadow.png",off: 20, trending: false, price : 699, des : "lorem1234"},
    {name : "Lip Oil", companyName : "elf", category : "beauty",src : "assets/IMAGES/Beauty/Lip oil.png",off: 0, trending: false, price: 600, des : "lorem1234"},
    {name : "Lip Gloss", companyName : "elf", category : "beauty",src : "assets/IMAGES/Beauty/Lip gloss.png",off: 0, trending: false, price : 500, des : "lorem1234"},
    {name : "Makeup Brush Set", companyName : "Huda Beauty", category : "beauty",src : "assets/IMAGES/Beauty/Makeup brush set.png",off: 50, trending: false, price : 500, des : "lorem1234"},
    {name : "Retinol Serum", companyName : "CeraVe", category : "beauty",src : "assets/IMAGES/Beauty/Retinol serum.png",off: 40, trending: false, price : 500,des : "lorem1234"},
    {name : "Vitamin-C Super Serum", companyName : "Saeed Ghani", category : "beauty",src : "assets/IMAGES/Beauty/Vitamin C super serum.png",off: 0, trending: false, price : 500, des : "lorem1234"},
  
     {name : "Blind Spot Mirror", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Blind Spot mirror.png",off: 0, trending: false, price : 5000, des : ""},
     {name : "Car Care Kit", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Car Care kit.png",off: 10, trending: false, price : 900, des : ""},
     {name : "Car Jump Starter", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Car jump Starter.png",off: 20, trending: false, price : 2000, des : ""},
     {name : "Carrera Hard Wax", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Carrera Hard wax.png",off: 0, trending: false, price : 9000, des : ""},
     {name : "Emergency Seat Belt Cutter", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Emergency seatbelt cutter and window hammer.png",off: 50, trending: false, price : 800, des : ""},
     {name : "Floor mats", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Emergency seatbelt cutter and window hammer.png",off: 0, trending: false, price : 5500, des : ""},
     {name : "Maintainance Log Book", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Maintenance Log Book.png",off: 30, trending: false, price : 1000, des : ""},
     {name : "Mobile Stand", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Mobile stand.png",off: 40, trending: false, price : 1100, des : ""},
     {name : "Portable Tyre Inflator", companyName : "", category : "Automotive",src : "assets/IMAGES/Automotive/Portable tire inflator.png",off: 0, trending: false, price : 9000, des : ""},

     {name : "Head Set", companyName : "", category : "Electronics",src : "assets/IMAGES/Electronics/Headset.png",off: 10, trending: true, price : 2000, des : ""},
     {name : "Wireless Printer", companyName : "", category : "Electronics",src : "assets/IMAGES/Electronics/Wireless printer.jpg",off: 20, trending: false, price : 5600, des : ""},
     {name : "Wireless Earbuds", companyName : "", category : "Electronics",src : "assets/IMAGES/Electronics/Wireless Earbuds.png",off: 0, trending: false, price : 1000, des : ""},
     {name : "Tripod", companyName : "", category : "Electronics",src : "assets/IMAGES/Electronics/Tripod.png",off: 60, trending: false, price : 500, des : ""},
     {name : "Watch", companyName : "", category : "Electronics",src : "assets/IMAGES/Electronics/watch.jpg",off: 10, trending: false, price : 6000, des : ""},
     {name : "Portable Speaker", companyName : "", category : "Electronics",src : "assets/IMAGES/Electronics/Protable speaker.png",off: 0, trending: false, price : 600, des : ""},
     {name : "Wifi Amplifier", companyName : "", category : "Electronics",src : "",off: 40, trending: false, price : 900, des : ""},
     {name : "Multi Charging Cable", companyName : "", category : "Electronics",src : "assets/IMAGES/Electronics/WIFI amplifier.png",off: 0, trending: false, price : 500, des : ""},
     {name : "CCTV Camera", companyName : "", category : "Electronics",src : "assets/IMAGES/Electronics/CCTV Camera.png",off: 0, trending: false, price : 9000, des : ""},

     {name : "Baggy Pents For Women", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Baggy pent for women.png",off: 10, trending: false, price : 600, des : ""},
     {name : "Blazer For Men", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Blazer for men.png",off: 50, trending: false, price : 600, des : ""},
     {name : "Brown Upper With White Shirt", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Brown upper with white shirt.jpg",off: 0, trending: true, price : 5000, des : ""},
     {name : "Guess Women Loven", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Guess women Loven.jpg",off: 0, trending: false, price : 1900, des : ""},
     {name : "Hand Bag", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Hand Bag.png",off: 5, trending: false, price : 6500, des : ""},
     {name : "Men Black Shade", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Men black shade.png",off: 10, trending: false, price : 500, des : ""},
     {name : "Shalwar Kameez", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Shalwar kameez for men.png",off: 0, trending: false, price : 6000, des : ""},
     {name : "Shirt with Skirt", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Shirt and Skirt.png",off: 40, trending: false, price : 1500, des : ""},
     {name : "SunGlasses for Women", companyName : "", category : "Fashion",src : "assets/IMAGES/Fashion/Sunglasses for women.jpg",off: 0, trending: false, price : 900, des : ""},

     {name : "Basket ball set", companyName : "", category : "Sports",src : "assets/IMAGES/sports/Basketball set.png",off: 10, trending: false, price : 600, des : ""},
     {name : "Cricket set", companyName : "", category : "Sports",src : "assets/IMAGES/sports/Cricket set.png",off: 0, trending: false, price : 800, des : ""},
     {name : "FootBAll", companyName : "", category : "Sports",src : "assets/IMAGES/sports/Football.png",off: 10, trending: false, price : 1500, des : ""},
     {name : "Hardball", companyName : "", category : "Sports",src : "assets/IMAGES/sports/Hard Ball.png",off: 40, trending: false, price : 600, des : ""},
     {name : "Hockey set", companyName : "", category : "Sports",src : "assets/IMAGES/sports/Hockey set.png",off: 10, trending: false, price : 600, des : ""},
     {name : "Magnetic Dart Board Set", companyName : "", category : "Sports",src : "assets/IMAGES/sports/Magnetic dart board set.png",off: 10, trending: false, price : 600, des : ""},
     {name : "Table Tennis Set", companyName : "", category : "Sports",src : "assets/IMAGES/sports/Table tennis set.png",off: 10, trending: false, price : 1600, des : ""},
     {name : "Wooden Chess Set", companyName : "", category : "Sports",src : "assets/IMAGES/sports/Wooden chess set.png",off: 0, trending: true, price : 3000, des : ""},
     {name : "Yonex Racket", companyName : "", category : "Sports",src : "assets/IMAGES/sports/yonex Racket.png",off: 10, trending: false, price : 900, des : ""},

          {name : "Assingment Paper", companyName : "", category : "Stationery",src : "assets/IMAGES/Stationary/Assignment paper.png",off: 0, trending: false, price : 500, des : ""},
          {name : "Gel Pens", companyName : "", category : "Stationery",src : "assets/IMAGES/Stationary/coorful gel pens.png",off: 10, trending: false, price : 900, des : ""},
          {name : "Desk Writing Pad", companyName : "", category : "Stationery",src : "assets/IMAGES/Stationary/Desk writing pad.png",off: 0, trending: false, price : 800, des : ""},
          {name : "Envelopes", companyName : "", category : "Stationery",src : "assets/IMAGES/Stationary/Envelopes.png",off: 0, trending: true, price : 900, des : ""},
          {name : "Notebook", companyName : "", category : "Stationery",src : "assets/IMAGES/Stationary/Notebook.png",off: 20, trending: false, price : 300, des : ""},
          {name : "Paper Clamps", companyName : "", category : "Stationery",src : "assets/IMAGES/Stationary/paperclamps.png",off: 0, trending: false, price : 200, des : ""},
          {name : "Pen Holder", companyName : "", category : "Stationery",src : "assets/IMAGES/Stationary/Pen holder.png",off: 0, trending: false, price : 200, des : ""},
          {name : "Stickey Notes", companyName : "", category : "Stationery",src : "assets/IMAGES/Stationary/Sticky notes.png",off: 0, trending: false, price : 100, des : ""},

     {name : "Buzz LIght Year Talking Action ", companyName : "", category : "Toys",src : "assets/IMAGES/Toys/Buzz lightyear talking action.png",off: 0, trending: true, price : 9000, des : ""},
     {name : "Jenga", companyName : "", category : "Toys",src : "assets/IMAGES/Toys/Jenga.png",off: 10, trending: false, price : 1700, des : ""},
     {name : "Kids Castle Play Tent", companyName : "", category : "Toys",src : "assets/IMAGES/Toys/Kids castle play tent.png",off: 20, trending: false, price : 500, des : ""},
     {name : "Mimicking Dancing Cactus", companyName : "", category : "Toys",src : "assets/IMAGES/Toys/mimicking danicng cactus.png",off: 0, trending: false, price : 2000, des : ""},
     {name : "Nerf Gun", companyName : "", category : "Toys",src : "assets/IMAGES/Toys/Nerf gun.png",off: 10, trending: false, price : 2000, des : ""},
     {name : "Pogo Stick", companyName : "", category : "Toys",src : "assets/IMAGES/Toys/Pogo stick.png",off: 0, trending: false, price : 800, des : ""},
     {name : "Posable Doll Set", companyName : "", category : "Toys",src : "assets/IMAGES/Toys/Posable doll set.png",off: 0, trending: false, price : 2000, des : ""},
     {name : "RC car", companyName : "", category : "Toys",src : "assets/IMAGES/Toys/RC car.png",off: 10, trending: false, price : 5000, des : ""},

];